---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - networking.kubegems.io
  resources:
  - nginxingresscontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.kubegems.io
  resources:
  - nginxingresscontrollers/finalizers
  verbs:
  - update
- apiGroups:
  - networking.kubegems.io
  resources:
  - nginxingresscontrollers/status
  verbs:
  - get
  - patch
  - update
