apiVersion: networking.kubegems.io/v1beta1
kind: NginxIngressController
metadata:
  name: cao
  namespace: cao
spec:
  image:
    pullPolicy: IfNotPresent
    repository: registry.k8s.io/ingress-nginx/controller
    tag: v1.3.0
  replicas: 1
  ingressClass: cao
  service:
    extraAnnotations:
      cao: nimab
    extraLabels:
      cao: nima
    type: NodePort
  workload:
    extraLabels:
      cao: nima
    resources:
      requests:
        cpu: 200m
        memory: 200Mi
  watchNamespace: ""
  configMapData:
    error-log-path: "/var/log/nginx/error.log"
