apiVersion: networking.kubegems.io/v1beta1
kind: NginxIngressController
metadata:
  name: cao
  namespace: cao
spec:
  image:
    pullPolicy: IfNotPresent
    repository: registry.k8s.io/ingress-nginx/controller
    tag: v1.3.0
  replicas: 1
  ingressClass: cao
  service:
    extraAnnotations:
      mykey: myvalue
    extraLabels:
      mykey: myvalue
    type: NodePort
  workload:
    extraLabels:
      mykey: myvalue
    resources:
      requests:
        cpu: 200m
        memory: 200Mi
  watchNamespace: "" # all ns
  # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
  configMapData:
    error-log-path: "/var/log/nginx/error.log"
